#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

/* Remaining keys:
- arrow keys
- ! @ £ $ % ^ & * #
- - _ + = ; :
- " ' \ / ? | ~ `
- , < . >
- Play, Pause, Next, Previous, Volume Up, Volume Down
- Brightness Up, Brightness Down
*/

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

/* Layer 1: Default/Base
+-------+-------+-------+-------+-------+   +-------+-------+-------+-------+-------+
|   q   |   w   |   f   |   p   |   b   |   |   j   |   l   |   u   |   y   | bkspc |
+-------+-------+-------+-------+-------+   +-------+-------+-------+-------+-------+
|   a   |   r   | alt/s | cmd/t |   g   |   |   m   | cmd/n | alt/e |   i   |   o   |
+-------+-------+-------+-------+-------+   +-------+-------+-------+-------+-------+
|   z   |   x   |   c   |   d   |   v   |   |   k   |   h   |   ,   |   .   |   /   |
+-------+-------+-------+-------+-------+   +-------+-------+-------+-------+-------+
                        |meh sft|  etr  |   | space |   L1  |
                        +-------+-------+   +-------+-------+
*/
[0] = LAYOUT(
KC_Q, KC_W, KC_F,                 KC_P,             KC_B,      KC_J, KC_L,             KC_U,    KC_Y,   KC_BSPC,
KC_A, KC_R, MT(KC_LEFT_ALT,KC_S), MT(KC_LGUI,KC_T), KC_G,      KC_M, MT(KC_RGUI,KC_N), MT(KC_RIGHT_ALT,KC_E),    KC_I,   KC_O,
KC_Z, KC_X, KC_C,                 KC_D,             KC_V,      KC_K, KC_H,             KC_COMM, KC_DOT, KC_SLSH,
                       MT(MOD_MEH,KC_LEFT_SHIFT), KC_ENT,      KC_SPC, TO(1)
),

/* Layer 2: Symbols
+-------+-------+-------+-------+-------+   +-------+-------+-------+-------+-------+
|       |       |       |       |       |   |       |       |       |       |       |
+-------+-------+-------+-------+-------+   +-------+-------+-------+-------+-------+
|       |       |  { [  |  } ]  |       |   |       |   (   |   )   |       |       |
+-------+-------+-------+-------+-------+   +-------+-------+-------+-------+-------+
|       |       |       |       |       |   |       |       |       |       |       |
+-------+-------+-------+-------+-------+   +-------+-------+-------+-------+-------+
                        |   L0  |       |   |       |       |
                        +-------+-------+   +-------+-------+
*/
[1] = LAYOUT(
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,     KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
KC_TRNS, KC_TRNS, KC_LBRC, KC_RBRC, KC_TRNS,     KC_TRNS, KC_LPRN, KC_RPRN, KC_TRNS, KC_TRNS,
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,     KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                           TO(0),   KC_TRNS,     KC_TRNS, KC_TRNS
),

/* Layer 3: Numpad, Mouse, Controls, etc.
+-------+-------+-------+-------+-------+   +-------+-------+-------+-------+-------+
|       |       |       |       |       |   |       |   7   |   8   |   9   |       |
+-------+-------+-------+-------+-------+   +-------+-------+-------+-------+-------+
|       |       |       |       |       |   |       |   4   |   5   |   6   |       |
+-------+-------+-------+-------+-------+   +-------+-------+-------+-------+-------+
|       |       |       |       |       |   |       |   1   |   2   |   3   |       |
+-------+-------+-------+-------+-------+   +-------+-------+-------+-------+-------+
                        |   L0  |       |   |       |   0   |
                        +-------+-------+   +-------+-------+
*/
[2] = LAYOUT(
KC_TRNS, KC_BTN1, KC_MS_U, KC_BTN2, KC_TRNS,     KC_TRNS, KC_P7, KC_P8, KC_P9, KC_TRNS,
KC_TRNS, KC_MS_L, KC_MS_D, KC_MS_R, KC_TRNS,     KC_TRNS, KC_P4, KC_P5, KC_P6, KC_TRNS,
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,     KC_TRNS, KC_P1, KC_P2, KC_P3, KC_TRNS,
                           TO(0),   KC_TRNS,     KC_TRNS, KC_P0
),

/* Layer 4: Mouse, etc.
+-------+-------+-------+-------+-------+   +-------+-------+-------+-------+-------+
|       | l clk |  m up | r clk |       |   |       |       |       |       |       |
+-------+-------+-------+-------+-------+   +-------+-------+-------+-------+-------+
|       | m lft | m dwn | m rgt |       |   |       |       |       |       |       |
+-------+-------+-------+-------+-------+   +-------+-------+-------+-------+-------+
|       |       |       |       |       |   |       |       |       |       |       |
+-------+-------+-------+-------+-------+   +-------+-------+-------+-------+-------+
                        |   L0  |       |   |       |       |
                        +-------+-------+   +-------+-------+
*/
[3] = LAYOUT(
KC_TRNS, KC_BTN1, KC_MS_U, KC_BTN2, KC_TRNS,     KC_TRNS, KC_P7, KC_P8, KC_P9, KC_TRNS,
KC_TRNS, KC_MS_L, KC_MS_D, KC_MS_R, KC_TRNS,     KC_TRNS, KC_P4, KC_P5, KC_P6, KC_TRNS,
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,     KC_TRNS, KC_P1, KC_P2, KC_P3, KC_TRNS,
                           TO(0),   KC_TRNS,     KC_TRNS, KC_P0
),

/* Layer 5: Gaming
+-------+-------+-------+-------+-------+   +-------+-------+-------+-------+-------+
|  esc  |   q   |   w   |   e   |   r   |   |   L0  |       |       |       |       |
+-------+-------+-------+-------+-------+   +-------+-------+-------+-------+-------+
|  sft  |   a   |   s   |   d   |   f   |   |       |       |       |       |       |
+-------+-------+-------+-------+-------+   +-------+-------+-------+-------+-------+
|  ctl  |   z   |   x   |   c   |   v   |   |       |       |       |       |       |
+-------+-------+-------+-------+-------+   +-------+-------+-------+-------+-------+
                        |       | space |   |       |       |
                        +-------+-------+   +-------+-------+
*/
[4] = LAYOUT(
KC_ESC,  KC_Q, KC_W, KC_E, KC_R,      TO(0),   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
KC_LSFT, KC_A, KC_S, KC_D, KC_F,      KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
KC_LCTL, KC_Z, KC_X, KC_C, KC_V,      KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                  KC_TRNS, KC_SPC,    KC_TRNS, KC_TRNS
)
};